---
server_url: http://awx.example.com
login_user: admin
login_password: h1y9E6s9tr

- hosts: all
  gather_facts: no
  tasks:  
  - name: restart postgresql
    win_service:
      name: postgresql-x64-13
      state: restarted
  
