---
- hosts: all
  gather_facts: yes
  tasks:
  - name: ping
    win_ping:
  - name: Download the 7-Zip package
    win_get_url:
      url: https://www.7-zip.org/a/7z1701-x64.msi
      dest: C:\temp\7z.msi

